/* capitals.ts — capital city of each country with its IANA timezone.
 * Used to populate the add-zone autocomplete with global coverage. */

import type { TzPreset } from "./data";

export const CAPITAL_PRESETS: TzPreset[] = [
  // Africa
  { city: "Algiers", region: "Algeria", tz: "Africa/Algiers" },
  { city: "Luanda", region: "Angola", tz: "Africa/Luanda" },
  { city: "Porto-Novo", region: "Benin", tz: "Africa/Porto-Novo" },
  { city: "Gaborone", region: "Botswana", tz: "Africa/Gaborone" },
  { city: "Ouagadougou", region: "Burkina Faso", tz: "Africa/Ouagadougou" },
  { city: "Gitega", region: "Burundi", tz: "Africa/Bujumbura" },
  { city: "Praia", region: "Cabo Verde", tz: "Atlantic/Cape_Verde" },
  { city: "Yaoundé", region: "Cameroon", tz: "Africa/Douala" },
  { city: "Bangui", region: "Central African Republic", tz: "Africa/Bangui" },
  { city: "N'Djamena", region: "Chad", tz: "Africa/Ndjamena" },
  { city: "Moroni", region: "Comoros", tz: "Indian/Comoro" },
  { city: "Brazzaville", region: "Congo", tz: "Africa/Brazzaville" },
  { city: "Kinshasa", region: "DR Congo", tz: "Africa/Kinshasa" },
  { city: "Djibouti", region: "Djibouti", tz: "Africa/Djibouti" },
  { city: "Cairo", region: "Egypt", tz: "Africa/Cairo" },
  { city: "Malabo", region: "Equatorial Guinea", tz: "Africa/Malabo" },
  { city: "Asmara", region: "Eritrea", tz: "Africa/Asmara" },
  { city: "Mbabane", region: "Eswatini", tz: "Africa/Mbabane" },
  { city: "Addis Ababa", region: "Ethiopia", tz: "Africa/Addis_Ababa" },
  { city: "Libreville", region: "Gabon", tz: "Africa/Libreville" },
  { city: "Banjul", region: "Gambia", tz: "Africa/Banjul" },
  { city: "Accra", region: "Ghana", tz: "Africa/Accra" },
  { city: "Conakry", region: "Guinea", tz: "Africa/Conakry" },
  { city: "Bissau", region: "Guinea-Bissau", tz: "Africa/Bissau" },
  { city: "Yamoussoukro", region: "Ivory Coast", tz: "Africa/Abidjan" },
  { city: "Nairobi", region: "Kenya", tz: "Africa/Nairobi" },
  { city: "Maseru", region: "Lesotho", tz: "Africa/Maseru" },
  { city: "Monrovia", region: "Liberia", tz: "Africa/Monrovia" },
  { city: "Tripoli", region: "Libya", tz: "Africa/Tripoli" },
  { city: "Antananarivo", region: "Madagascar", tz: "Indian/Antananarivo" },
  { city: "Lilongwe", region: "Malawi", tz: "Africa/Blantyre" },
  { city: "Bamako", region: "Mali", tz: "Africa/Bamako" },
  { city: "Nouakchott", region: "Mauritania", tz: "Africa/Nouakchott" },
  { city: "Port Louis", region: "Mauritius", tz: "Indian/Mauritius" },
  { city: "Rabat", region: "Morocco", tz: "Africa/Casablanca" },
  { city: "Maputo", region: "Mozambique", tz: "Africa/Maputo" },
  { city: "Windhoek", region: "Namibia", tz: "Africa/Windhoek" },
  { city: "Niamey", region: "Niger", tz: "Africa/Niamey" },
  { city: "Abuja", region: "Nigeria", tz: "Africa/Lagos" },
  { city: "Kigali", region: "Rwanda", tz: "Africa/Kigali" },
  { city: "São Tomé", region: "São Tomé and Príncipe", tz: "Africa/Sao_Tome" },
  { city: "Dakar", region: "Senegal", tz: "Africa/Dakar" },
  { city: "Victoria", region: "Seychelles", tz: "Indian/Mahe" },
  { city: "Freetown", region: "Sierra Leone", tz: "Africa/Freetown" },
  { city: "Mogadishu", region: "Somalia", tz: "Africa/Mogadishu" },
  { city: "Pretoria", region: "South Africa", tz: "Africa/Johannesburg" },
  { city: "Juba", region: "South Sudan", tz: "Africa/Juba" },
  { city: "Khartoum", region: "Sudan", tz: "Africa/Khartoum" },
  { city: "Dodoma", region: "Tanzania", tz: "Africa/Dar_es_Salaam" },
  { city: "Lomé", region: "Togo", tz: "Africa/Lome" },
  { city: "Tunis", region: "Tunisia", tz: "Africa/Tunis" },
  { city: "Kampala", region: "Uganda", tz: "Africa/Kampala" },
  { city: "Lusaka", region: "Zambia", tz: "Africa/Lusaka" },
  { city: "Harare", region: "Zimbabwe", tz: "Africa/Harare" },

  // Americas
  { city: "Buenos Aires", region: "Argentina", tz: "America/Argentina/Buenos_Aires" },
  { city: "Nassau", region: "Bahamas", tz: "America/Nassau" },
  { city: "Bridgetown", region: "Barbados", tz: "America/Barbados" },
  { city: "Belmopan", region: "Belize", tz: "America/Belize" },
  { city: "Sucre", region: "Bolivia", tz: "America/La_Paz" },
  { city: "Brasília", region: "Brazil", tz: "America/Sao_Paulo" },
  { city: "Ottawa", region: "Canada", tz: "America/Toronto" },
  { city: "Santiago", region: "Chile", tz: "America/Santiago" },
  { city: "Bogotá", region: "Colombia", tz: "America/Bogota" },
  { city: "San José", region: "Costa Rica", tz: "America/Costa_Rica" },
  { city: "Havana", region: "Cuba", tz: "America/Havana" },
  { city: "Roseau", region: "Dominica", tz: "America/Dominica" },
  { city: "Santo Domingo", region: "Dominican Republic", tz: "America/Santo_Domingo" },
  { city: "Quito", region: "Ecuador", tz: "America/Guayaquil" },
  { city: "San Salvador", region: "El Salvador", tz: "America/El_Salvador" },
  { city: "Saint George's", region: "Grenada", tz: "America/Grenada" },
  { city: "Guatemala City", region: "Guatemala", tz: "America/Guatemala" },
  { city: "Georgetown", region: "Guyana", tz: "America/Guyana" },
  { city: "Port-au-Prince", region: "Haiti", tz: "America/Port-au-Prince" },
  { city: "Tegucigalpa", region: "Honduras", tz: "America/Tegucigalpa" },
  { city: "Kingston", region: "Jamaica", tz: "America/Jamaica" },
  { city: "Mexico City", region: "Mexico", tz: "America/Mexico_City" },
  { city: "Managua", region: "Nicaragua", tz: "America/Managua" },
  { city: "Panama City", region: "Panama", tz: "America/Panama" },
  { city: "Asunción", region: "Paraguay", tz: "America/Asuncion" },
  { city: "Lima", region: "Peru", tz: "America/Lima" },
  { city: "Basseterre", region: "Saint Kitts and Nevis", tz: "America/St_Kitts" },
  { city: "Castries", region: "Saint Lucia", tz: "America/St_Lucia" },
  { city: "Kingstown", region: "Saint Vincent", tz: "America/St_Vincent" },
  { city: "Paramaribo", region: "Suriname", tz: "America/Paramaribo" },
  { city: "Port of Spain", region: "Trinidad and Tobago", tz: "America/Port_of_Spain" },
  { city: "Washington", region: "USA", tz: "America/New_York" },
  { city: "Montevideo", region: "Uruguay", tz: "America/Montevideo" },
  { city: "Caracas", region: "Venezuela", tz: "America/Caracas" },

  // Asia
  { city: "Kabul", region: "Afghanistan", tz: "Asia/Kabul" },
  { city: "Yerevan", region: "Armenia", tz: "Asia/Yerevan" },
  { city: "Baku", region: "Azerbaijan", tz: "Asia/Baku" },
  { city: "Manama", region: "Bahrain", tz: "Asia/Bahrain" },
  { city: "Dhaka", region: "Bangladesh", tz: "Asia/Dhaka" },
  { city: "Thimphu", region: "Bhutan", tz: "Asia/Thimphu" },
  { city: "Bandar Seri Begawan", region: "Brunei", tz: "Asia/Brunei" },
  { city: "Phnom Penh", region: "Cambodia", tz: "Asia/Phnom_Penh" },
  { city: "Beijing", region: "China", tz: "Asia/Shanghai" },
  { city: "Nicosia", region: "Cyprus", tz: "Asia/Nicosia" },
  { city: "Dili", region: "East Timor", tz: "Asia/Dili" },
  { city: "Tbilisi", region: "Georgia", tz: "Asia/Tbilisi" },
  { city: "New Delhi", region: "India", tz: "Asia/Kolkata" },
  { city: "Jakarta", region: "Indonesia", tz: "Asia/Jakarta" },
  { city: "Tehran", region: "Iran", tz: "Asia/Tehran" },
  { city: "Baghdad", region: "Iraq", tz: "Asia/Baghdad" },
  { city: "Jerusalem", region: "Israel", tz: "Asia/Jerusalem" },
  { city: "Tokyo", region: "Japan", tz: "Asia/Tokyo" },
  { city: "Amman", region: "Jordan", tz: "Asia/Amman" },
  { city: "Astana", region: "Kazakhstan", tz: "Asia/Almaty" },
  { city: "Kuwait City", region: "Kuwait", tz: "Asia/Kuwait" },
  { city: "Bishkek", region: "Kyrgyzstan", tz: "Asia/Bishkek" },
  { city: "Vientiane", region: "Laos", tz: "Asia/Vientiane" },
  { city: "Beirut", region: "Lebanon", tz: "Asia/Beirut" },
  { city: "Kuala Lumpur", region: "Malaysia", tz: "Asia/Kuala_Lumpur" },
  { city: "Malé", region: "Maldives", tz: "Indian/Maldives" },
  { city: "Ulaanbaatar", region: "Mongolia", tz: "Asia/Ulaanbaatar" },
  { city: "Naypyidaw", region: "Myanmar", tz: "Asia/Yangon" },
  { city: "Kathmandu", region: "Nepal", tz: "Asia/Kathmandu" },
  { city: "Pyongyang", region: "North Korea", tz: "Asia/Pyongyang" },
  { city: "Muscat", region: "Oman", tz: "Asia/Muscat" },
  { city: "Islamabad", region: "Pakistan", tz: "Asia/Karachi" },
  { city: "Manila", region: "Philippines", tz: "Asia/Manila" },
  { city: "Doha", region: "Qatar", tz: "Asia/Qatar" },
  { city: "Riyadh", region: "Saudi Arabia", tz: "Asia/Riyadh" },
  { city: "Singapore", region: "Singapore", tz: "Asia/Singapore" },
  { city: "Seoul", region: "South Korea", tz: "Asia/Seoul" },
  { city: "Colombo", region: "Sri Lanka", tz: "Asia/Colombo" },
  { city: "Damascus", region: "Syria", tz: "Asia/Damascus" },
  { city: "Taipei", region: "Taiwan", tz: "Asia/Taipei" },
  { city: "Dushanbe", region: "Tajikistan", tz: "Asia/Dushanbe" },
  { city: "Bangkok", region: "Thailand", tz: "Asia/Bangkok" },
  { city: "Ankara", region: "Turkey", tz: "Europe/Istanbul" },
  { city: "Ashgabat", region: "Turkmenistan", tz: "Asia/Ashgabat" },
  { city: "Abu Dhabi", region: "UAE", tz: "Asia/Dubai" },
  { city: "Tashkent", region: "Uzbekistan", tz: "Asia/Tashkent" },
  { city: "Hanoi", region: "Vietnam", tz: "Asia/Ho_Chi_Minh" },
  { city: "Sana'a", region: "Yemen", tz: "Asia/Aden" },

  // Europe
  { city: "Tirana", region: "Albania", tz: "Europe/Tirane" },
  { city: "Andorra la Vella", region: "Andorra", tz: "Europe/Andorra" },
  { city: "Vienna", region: "Austria", tz: "Europe/Vienna" },
  { city: "Minsk", region: "Belarus", tz: "Europe/Minsk" },
  { city: "Brussels", region: "Belgium", tz: "Europe/Brussels" },
  { city: "Sarajevo", region: "Bosnia and Herzegovina", tz: "Europe/Sarajevo" },
  { city: "Sofia", region: "Bulgaria", tz: "Europe/Sofia" },
  { city: "Zagreb", region: "Croatia", tz: "Europe/Zagreb" },
  { city: "Prague", region: "Czechia", tz: "Europe/Prague" },
  { city: "Copenhagen", region: "Denmark", tz: "Europe/Copenhagen" },
  { city: "Tallinn", region: "Estonia", tz: "Europe/Tallinn" },
  { city: "Helsinki", region: "Finland", tz: "Europe/Helsinki" },
  { city: "Paris", region: "France", tz: "Europe/Paris" },
  { city: "Berlin", region: "Germany", tz: "Europe/Berlin" },
  { city: "Athens", region: "Greece", tz: "Europe/Athens" },
  { city: "Budapest", region: "Hungary", tz: "Europe/Budapest" },
  { city: "Reykjavík", region: "Iceland", tz: "Atlantic/Reykjavik" },
  { city: "Dublin", region: "Ireland", tz: "Europe/Dublin" },
  { city: "Rome", region: "Italy", tz: "Europe/Rome" },
  { city: "Pristina", region: "Kosovo", tz: "Europe/Belgrade" },
  { city: "Riga", region: "Latvia", tz: "Europe/Riga" },
  { city: "Vaduz", region: "Liechtenstein", tz: "Europe/Vaduz" },
  { city: "Vilnius", region: "Lithuania", tz: "Europe/Vilnius" },
  { city: "Luxembourg", region: "Luxembourg", tz: "Europe/Luxembourg" },
  { city: "Valletta", region: "Malta", tz: "Europe/Malta" },
  { city: "Chișinău", region: "Moldova", tz: "Europe/Chisinau" },
  { city: "Monaco", region: "Monaco", tz: "Europe/Monaco" },
  { city: "Podgorica", region: "Montenegro", tz: "Europe/Podgorica" },
  { city: "Amsterdam", region: "Netherlands", tz: "Europe/Amsterdam" },
  { city: "Skopje", region: "North Macedonia", tz: "Europe/Skopje" },
  { city: "Oslo", region: "Norway", tz: "Europe/Oslo" },
  { city: "Warsaw", region: "Poland", tz: "Europe/Warsaw" },
  { city: "Lisbon", region: "Portugal", tz: "Europe/Lisbon" },
  { city: "Bucharest", region: "Romania", tz: "Europe/Bucharest" },
  { city: "Moscow", region: "Russia", tz: "Europe/Moscow" },
  { city: "San Marino", region: "San Marino", tz: "Europe/San_Marino" },
  { city: "Belgrade", region: "Serbia", tz: "Europe/Belgrade" },
  { city: "Bratislava", region: "Slovakia", tz: "Europe/Bratislava" },
  { city: "Ljubljana", region: "Slovenia", tz: "Europe/Ljubljana" },
  { city: "Madrid", region: "Spain", tz: "Europe/Madrid" },
  { city: "Stockholm", region: "Sweden", tz: "Europe/Stockholm" },
  { city: "Bern", region: "Switzerland", tz: "Europe/Zurich" },
  { city: "Kyiv", region: "Ukraine", tz: "Europe/Kyiv" },
  { city: "London", region: "UK", tz: "Europe/London" },
  { city: "Vatican City", region: "Vatican", tz: "Europe/Vatican" },

  // Oceania
  { city: "Canberra", region: "Australia", tz: "Australia/Sydney" },
  { city: "Suva", region: "Fiji", tz: "Pacific/Fiji" },
  { city: "Tarawa", region: "Kiribati", tz: "Pacific/Tarawa" },
  { city: "Majuro", region: "Marshall Islands", tz: "Pacific/Majuro" },
  { city: "Palikir", region: "Micronesia", tz: "Pacific/Pohnpei" },
  { city: "Yaren", region: "Nauru", tz: "Pacific/Nauru" },
  { city: "Wellington", region: "New Zealand", tz: "Pacific/Auckland" },
  { city: "Ngerulmud", region: "Palau", tz: "Pacific/Palau" },
  { city: "Port Moresby", region: "Papua New Guinea", tz: "Pacific/Port_Moresby" },
  { city: "Apia", region: "Samoa", tz: "Pacific/Apia" },
  { city: "Honiara", region: "Solomon Islands", tz: "Pacific/Guadalcanal" },
  { city: "Nuku'alofa", region: "Tonga", tz: "Pacific/Tongatapu" },
  { city: "Funafuti", region: "Tuvalu", tz: "Pacific/Funafuti" },
  { city: "Port Vila", region: "Vanuatu", tz: "Pacific/Efate" },
];
